# Generated by Django 6.0.4 on 2026-04-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='es_oferta',
            field=models.BooleanField(default=False, verbose_name='¿Es oferta?'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio de oferta'),
        ),
    ]
