# Generated by Django 6.0.4 on 2026-07-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_perfume_es_oferta_perfume_precio_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPortada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Referencia interna (no se muestra en la web).', max_length=120)),
                ('imagen', models.ImageField(help_text='Imagen de fondo. Recomendado: horizontal, mínimo 1920px de ancho.', upload_to='portada/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen de portada',
                'verbose_name_plural': 'Imágenes de portada (carrusel)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
