# Generated by Django 6.0.4 on 2026-07-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_imagenportada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Ej: '2 Perfumes por $10.000' o 'Combo Pareja'.", max_length=120)),
                ('descripcion', models.CharField(blank=True, help_text='Texto corto que explica la promoción.', max_length=255)),
                ('precio', models.PositiveIntegerField(help_text='Precio total de la promoción, ej: 10000.')),
                ('etiqueta', models.CharField(blank=True, default='Promoción', help_text="Etiqueta que aparece sobre la tarjeta (ej: 'Oferta', '2x1').", max_length=40)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen opcional para la promoción.', null=True, upload_to='promociones/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.')),
                ('activo', models.BooleanField(default=True)),
                ('perfumes', models.ManyToManyField(blank=True, help_text='Perfumes incluidos en la promoción (opcional).', related_name='promociones', to='catalogo.perfume')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
