# Generated by Django 6.0.4 on 2026-07-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='perfumes/galeria/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='catalogo.perfume')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Galería de imágenes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente.', max_length=80)),
                ('calificacion', models.PositiveSmallIntegerField(choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=5)),
                ('comentario', models.TextField()),
                ('aprobado', models.BooleanField(default=False, help_text='Marca para que la reseña aparezca en la web.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='catalogo.perfume')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha'],
            },
        ),
    ]
