# Generated by Django 6.0.4 on 2026-07-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_imagenperfume_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='notas_corazon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notas_fondo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notas_salida',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
