# Generated by Django 6.0.4 on 2026-07-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_perfume_notas_corazon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nuestra Historia', help_text='Título principal de la sección.', max_length=150)),
                ('subtitulo', models.CharField(blank=True, help_text='Frase corta bajo el título (opcional).', max_length=200)),
                ('contenido', models.TextField(help_text='Texto principal. Puedes separar en varios párrafos con saltos de línea.')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen destacada de la sección (opcional).', null=True, upload_to='nosotros/')),
                ('cita', models.CharField(blank=True, help_text='Frase destacada o cita al final (opcional).', max_length=255)),
                ('cita_autor', models.CharField(blank=True, default='Dirección Instinto Olfativo', help_text='Autor/firma de la cita.', max_length=120)),
                ('pilar1_titulo', models.CharField(blank=True, default='Autenticidad Absoluta', max_length=80)),
                ('pilar1_texto', models.TextField(blank=True)),
                ('pilar2_titulo', models.CharField(blank=True, default='Asesoría Experta', max_length=80)),
                ('pilar2_texto', models.TextField(blank=True)),
                ('pilar3_titulo', models.CharField(blank=True, default='Servicio Discreto', max_length=80)),
                ('pilar3_texto', models.TextField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Nosotros',
                'verbose_name_plural': 'Página Nosotros',
            },
        ),
    ]
