# Generated by Django 6.0.4 on 2026-07-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_paginanosotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginanosotros',
            name='contenido2',
            field=models.TextField(blank=True, help_text='Texto del segundo bloque (opcional).'),
        ),
        migrations.AddField(
            model_name='paginanosotros',
            name='contenido3',
            field=models.TextField(blank=True, help_text='Texto del tercer bloque (opcional).'),
        ),
        migrations.AddField(
            model_name='paginanosotros',
            name='subtitulo2',
            field=models.CharField(blank=True, help_text='Segundo subtítulo (opcional).', max_length=200),
        ),
        migrations.AddField(
            model_name='paginanosotros',
            name='subtitulo3',
            field=models.CharField(blank=True, help_text='Tercer subtítulo (opcional).', max_length=200),
        ),
    ]
