# Generated by Django 6.0.4 on 2026-07-29 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_paginanosotros_contenido2_paginanosotros_contenido3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, help_text='Nombre del cliente (opcional).', max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12)),
                ('total', models.PositiveIntegerField(default=0, help_text='Total en CLP.')),
                ('stock_descontado', models.BooleanField(default=False, help_text='Marca interna: evita descontar stock dos veces.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venta / Pedido',
                'verbose_name_plural': 'Ventas / Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre guardado (por si el perfume se elimina).', max_length=200)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('perfume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='catalogo.perfume')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogo.pedido')),
            ],
            options={
                'verbose_name': 'Producto del pedido',
                'verbose_name_plural': 'Productos del pedido',
            },
        ),
    ]
